// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    Badge: typeof import('./src/components/Badge.vue')['default']
    Footer: typeof import('./src/components/Footer.vue')['default']
    PiniaCart: typeof import('./src/components/PiniaCart.vue')['default']
    PiniaCheckout: typeof import('./src/components/PiniaCheckout.vue')['default']
    PiniaMarket: typeof import('./src/components/PiniaMarket.vue')['default']
  }
}

export { }
